# Numerical Python(Numpy) - Part1

In [21]:
# de facto standard (사실상의 표준)
import numpy as np

In [22]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [23]:
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [24]:
b = np.array([1,2,3])
b*3

array([3, 6, 9])

## 1. Numpy Dimensional array

In [25]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [26]:
type(a)

numpy.ndarray

In [27]:
a.dtype, a.shape

(dtype('float64'), (4,))

## 2. Array shape

In [28]:
# Vector(1D)
vector = np.array([1,4,5,8])
vector.shape

(4,)

In [29]:
# Matrix(2D)
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [30]:
# Tensor(more than 3D)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [31]:
tensor.shape

(2, 3, 4)

In [32]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [33]:
# count of el
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [35]:
# data type
# float32: 32bit로 표시 - single precision
# float64: 64bit로 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [36]:
b = np.array([1,2,3], dtype=np.int16)
b

array([1, 2, 3], dtype=int16)

### reshape

In [37]:
matrix.shape

(2, 3)

In [38]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [39]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
matrix.reshape(3, -1).shape

(3, 2)

In [41]:
tensor.reshape(4, -1).shape

(4, 6)

In [42]:
matrix.reshape(-1, )

array([1, 2, 3, 4, 5, 6])

In [43]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [44]:
matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### flatten

In [50]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [46]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### 3. Indexing & Slicing

### Indexing

In [47]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
matrix[0][1]

2

In [49]:
matrix[0,1]

2

In [51]:
tensor[1,1,2]

19

### Slicing

In [52]:
b = np.arange(16).reshape(4, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
# 5,6,9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [54]:
# 5,6,7, 9,10,11
b[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [55]:
# 1,3,9,11
b[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [56]:
# X는 앞에 3열, y는 마지막 열
X, y = b[:,:-1], b[:,-1]
X.shape, y.shape

((4, 3), (4,))