# Numpy Practice

In [27]:
import numpy as np

## Q1. Creating a matrix

In [28]:
np.arange(1, 11).reshape(2, -1)*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

## Q2. matrix indexing, slicing

In [29]:
m = np.arange(0, 15).reshape(3,-1)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
m[1,2], m[2,-1], m[1,1:3], m[1:,2], m[:2,-2:]

(7, 14, array([6, 7]), array([ 7, 12]), array([[3, 4],
        [8, 9]]))

## Q3. Boolean Indexing

In [31]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
f[f%3==0]

array([ 0,  3,  6,  9, 12])

In [33]:
f[f%4==1]

array([ 1,  5,  9, 13])

In [34]:
f[np.logical_and(f%3==0, f%4==1)]

array([9])

## Q4. Creating a matrix with eye()

In [35]:
np.eye(5, k=-1)*3 + np.eye(5)*2 + np.eye(5, k=1) 

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

## Q5. 0~10까지 랜덤 실수값으로 5 X 6 데이터 행렬 만들고 다음의 값을 구하시오

In [36]:
np.random.seed(2021)
m = np.random.uniform(0, 10, 30).reshape(5,6)
m

array([[6.05978279, 7.33369361, 1.38947157, 3.12673084, 9.97243281,
        1.28162375],
       [1.78993106, 7.52925429, 6.62160514, 7.84310132, 0.96894396,
        0.58571285],
       [9.6239599 , 6.16557444, 0.86629961, 5.61272363, 6.16524709,
        9.63843023],
       [5.74304294, 3.71160848, 4.52145244, 2.01850248, 5.69305118,
        1.95095974],
       [5.83704016, 4.76313474, 5.178144  , 8.23098634, 7.32225027,
        0.69056275]])

In [37]:
m.max(), m.sum(axis=1), m.max(axis=1), m.mean(axis=0), m.min(axis=0)

(9.972432813403188,
 array([29.16373537, 25.33854862, 38.07223489, 23.63861727, 32.02211826]),
 array([9.97243281, 7.84310132, 9.63843023, 5.74304294, 8.23098634]),
 array([5.81075137, 5.90065311, 3.71539455, 5.36640892, 6.02438506,
        2.82945787]),
 array([1.78993106, 3.71160848, 0.86629961, 2.01850248, 0.96894396,
        0.58571285]))

## Q6. 영어 성적 기준으로 각 열 재정렬

In [38]:
# 1행 학번, 2행 영어, 3행 수학 > 3개가 set로 같이 정렬되어야 한다.
arr = np.array([[1,2,3,4],
       [46,99,100,71],
       [81,59,90,100]])
arr

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [39]:
np.argsort(arr)

array([[0, 1, 2, 3],
       [0, 3, 1, 2],
       [1, 0, 2, 3]])

In [40]:
np.sort(arr)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [41]:
s = np.argsort(arr[1])
s

array([0, 3, 1, 2])

In [42]:
# des sort
s[::-1]

array([2, 1, 3, 0])

In [43]:
arr[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

## Q7. 주사위를 100번 던지는 가상 실험, 던져서 나오는  숫자 평균 구하기

In [47]:
np.random.seed(2021)
a = np.random.randint(1, 7, 100)
a

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [48]:
np.mean(a)

3.7

## Q8. 가격이 만원인 주식이 있다. 이 주식의 일간 수익률은 표준정규분포를 따른다. 250일 동안의 주기를 무작위로 생성

In [81]:
np.random.seed(2021)
stock_cost = 10000
benefit = np.random.randn(250, ) / 100
benefit

array([ 1.48860905e-02,  6.76010871e-03, -4.18451369e-03, -8.06520813e-03,
        5.55875832e-03, -7.05504286e-03,  1.13085826e-02,  6.45001837e-03,
        1.06413743e-03,  4.22154830e-03,  1.24206845e-03, -8.37953461e-03,
        4.09015705e-03,  1.02751219e-03, -1.90772239e-02,  1.10022430e-02,
       -1.40232506e-02, -2.25081267e-03, -1.33620597e-02,  3.03721514e-03,
       -7.20158835e-03,  2.54491460e-02,  1.31729112e-02,  7.26303019e-04,
       -2.56108138e-03,  1.38010408e-03,  1.14723599e-02,  1.37626076e-02,
       -4.72183967e-03,  5.24084896e-03,  1.48510793e-02,  1.48243225e-02,
        7.28130509e-03, -3.89648083e-03,  2.78893759e-03,  5.19001995e-04,
       -1.04474368e-02, -1.61507534e-03, -2.79353057e-02,  3.61648007e-03,
        2.40107579e-03,  4.77812285e-03,  2.08851935e-03,  9.17911635e-03,
       -1.41177784e-02,  1.22423572e-02, -5.45657718e-03,  9.06748053e-03,
       -9.82617236e-03, -6.33161892e-03,  8.25520240e-03, -1.28449686e-02,
       -3.47308784e-03, -

In [82]:
np.cumprod(benefit) * 10000

array([ 1.48860905e+002,  1.00631590e+000, -4.21094268e-003,
        3.39621291e-005,  1.88787268e-007, -1.33190227e-009,
       -1.50619268e-011, -9.71497045e-014, -1.03380636e-016,
       -4.36426350e-019, -5.42071398e-022,  4.54230604e-024,
        1.85787451e-026,  1.90898869e-029, -3.64182048e-031,
       -4.00681940e-033,  5.61886326e-035, -1.26470086e-037,
        1.68990084e-039,  5.13259240e-042, -3.69628176e-044,
       -9.40672143e-046, -1.23913906e-047, -8.99990441e-051,
        2.30494876e-053,  3.18106918e-056,  3.64943704e-058,
        5.02257698e-060, -2.37158033e-062, -1.24290943e-064,
       -1.84585464e-066, -2.73635445e-068, -1.99242316e-070,
        7.76343864e-073,  2.16517458e-075,  1.12372993e-078,
       -1.17400974e-080,  1.89611419e-083, -5.29685295e-085,
       -1.91559631e-087, -4.59949192e-090, -2.19769374e-092,
       -4.58992591e-095, -4.21314640e-097,  5.94802674e-099,
        7.28178680e-101, -3.97336317e-103, -3.60283932e-105,
        3.54021201e-107,