# Numpy Practice

In [2]:
import numpy as np

## Q1. Creating a matrix

In [3]:
np.arange(1, 11).reshape(2, -1)*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

## Q2. matrix indexing, slicing

In [4]:
m = np.arange(0, 15).reshape(3,-1)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
m[1,2], m[2,-1], m[1,1:3], m[1:,2], m[:2,-2:]

(7, 14, array([6, 7]), array([ 7, 12]), array([[3, 4],
        [8, 9]]))

## Q3. Boolean Indexing

In [6]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
f[f%3==0]

array([ 0,  3,  6,  9, 12])

In [8]:
f[f%4==1]

array([ 1,  5,  9, 13])

In [9]:
f[np.logical_and(f%3==0, f%4==1)]

array([9])

## Q4. Creating a matrix with eye()

In [10]:
np.eye(5, k=-1)*3 + np.eye(5)*2 + np.eye(5, k=1) 

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

## Q5. 0~10까지 랜덤 실수값으로 5 X 6 데이터 행렬 만들고 다음의 값을 구하시오

In [11]:
np.random.seed(2021)
m = np.random.uniform(0, 10, 30).reshape(5,6)
m

array([[6.05978279, 7.33369361, 1.38947157, 3.12673084, 9.97243281,
        1.28162375],
       [1.78993106, 7.52925429, 6.62160514, 7.84310132, 0.96894396,
        0.58571285],
       [9.6239599 , 6.16557444, 0.86629961, 5.61272363, 6.16524709,
        9.63843023],
       [5.74304294, 3.71160848, 4.52145244, 2.01850248, 5.69305118,
        1.95095974],
       [5.83704016, 4.76313474, 5.178144  , 8.23098634, 7.32225027,
        0.69056275]])

In [12]:
m.max(), m.sum(axis=1), m.max(axis=1), m.mean(axis=0), m.min(axis=0)

(9.972432813403188,
 array([29.16373537, 25.33854862, 38.07223489, 23.63861727, 32.02211826]),
 array([9.97243281, 7.84310132, 9.63843023, 5.74304294, 8.23098634]),
 array([5.81075137, 5.90065311, 3.71539455, 5.36640892, 6.02438506,
        2.82945787]),
 array([1.78993106, 3.71160848, 0.86629961, 2.01850248, 0.96894396,
        0.58571285]))

## Q6. 영어 성적 기준으로 각 열 재정렬

In [13]:
# 1행 학번, 2행 영어, 3행 수학 > 3개가 set로 같이 정렬되어야 한다.
arr = np.array([[1,2,3,4],
       [46,99,100,71],
       [81,59,90,100]])
arr

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [14]:
np.argsort(arr)

array([[0, 1, 2, 3],
       [0, 3, 1, 2],
       [1, 0, 2, 3]])

In [15]:
np.sort(arr)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [16]:
s = np.argsort(arr[1])
s

array([0, 3, 1, 2])

In [17]:
# des sort
s[::-1]

array([2, 1, 3, 0])

In [18]:
arr[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

## Q7. 주사위를 100번 던지는 가상 실험, 던져서 나오는  숫자 평균 구하기

In [19]:
np.random.seed(2021)
a = np.random.randint(1, 7, 100)
a

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [20]:
np.mean(a)

3.7

## Q8. 가격이 만원인 주식이 있다. 이 주식의 일간 수익률은 표준정규분포를 따른다. 250일 동안의 주기를 무작위로 생성

In [23]:
np.random.seed(2021)
price = 10000
rate = np.random.normal(0,0.01,10)
for i in range(10):
  price += np.round(price * rate[i])
  print(price, end=', ')

10149.0, 10218.0, 10175.0, 10093.0, 10149.0, 10077.0, 10191.0, 10257.0, 10268.0, 10311.0, 

In [24]:
np.random.seed(2021)
price_list = []
price = 10000
rate = np.random.normal(0,0.01,250)
for i in range(250):
  price += np.round(price * rate[i])
  price_list.append(int(price))

In [27]:
price_list[:10]

[10149, 10218, 10175, 10093, 10149, 10077, 10191, 10257, 10268, 10311]