# DataFrame Class

In [1]:
import numpy as np
import pandas as pd

# Make DataFrame

In [2]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [4]:
data = np.arange(24).reshape(4,6)
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역  2015  2010  2005  2000  2010-2015 증가율
서울   0     1     2     3     4              5
부산   6     7     8     9    10             11
인천  12    13    14    15    16             17
대구  18    19    20    21    22             23

In [5]:
df.지역.values

array([ 0,  6, 12, 18])

In [6]:
df['2015'].values

array([ 1,  7, 13, 19])

In [8]:
df.index.name = '도시'
df.columns.name = '특성'
df

특성  지역  2015  2010  2005  2000  2010-2015 증가율
도시                                           
서울   0     1     2     3     4              5
부산   6     7     8     9    10             11
인천  12    13    14    15    16             17
대구  18    19    20    21    22             23

In [9]:
df.T

도시             서울  부산  인천  대구
특성                           
지역              0   6  12  18
2015            1   7  13  19
2010            2   8  14  20
2005            3   9  15  21
2000            4  10  16  22
2010-2015 증가율   5  11  17  23

## col update, add, delete

In [10]:
df['2010-2015 증가율'] *= 100
df

특성  지역  2015  2010  2005  2000  2010-2015 증가율
도시                                           
서울   0     1     2     3     4            500
부산   6     7     8     9    10           1100
인천  12    13    14    15    16           1700
대구  18    19    20    21    22           2300

In [11]:
df['2020'] = [5, 11, 17, 23]
df

특성  지역  2015  2010  2005  2000  2010-2015 증가율  2020
도시                                                 
서울   0     1     2     3     4            500     5
부산   6     7     8     9    10           1100    11
인천  12    13    14    15    16           1700    17
대구  18    19    20    21    22           2300    23

In [12]:
del df['2020']
df

특성  지역  2015  2010  2005  2000  2010-2015 증가율
도시                                           
서울   0     1     2     3     4            500
부산   6     7     8     9    10           1100
인천  12    13    14    15    16           1700
대구  18    19    20    21    22           2300

## col indexing

In [13]:
df['지역'] # series

도시
서울     0
부산     6
인천    12
대구    18
Name: 지역, dtype: int64

In [14]:
df[['지역', '2015']] # DataFrame

특성  지역  2015
도시          
서울   0     1
부산   6     7
인천  12    13
대구  18    19

In [15]:
df[['지역']]

특성  지역
도시    
서울   0
부산   6
인천  12
대구  18

In [16]:
type(df['지역']), type(df[['지역']])

(pandas.core.series.Series, pandas.core.frame.DataFrame)

## row indexing

In [17]:
df['서울']

KeyError: ignored

In [18]:
df[:'서울']

특성  지역  2015  2010  2005  2000  2010-2015 증가율
도시                                           
서울   0     1     2     3     4            500

In [19]:
df[1:2]

특성  지역  2015  2010  2005  2000  2010-2015 증가율
도시                                           
부산   6     7     8     9    10           1100

In [20]:
df['부산':'인천']

특성  지역  2015  2010  2005  2000  2010-2015 증가율
도시                                           
부산   6     7     8     9    10           1100
인천  12    13    14    15    16           1700

In [21]:
df.head(3)

특성  지역  2015  2010  2005  2000  2010-2015 증가율
도시                                           
서울   0     1     2     3     4            500
부산   6     7     8     9    10           1100
인천  12    13    14    15    16           1700

## individual data indexing
- df['col name']['row name']

In [22]:
df['2015']['서울'], df['2015'][0] 

(1, 1)

## Quiz

In [23]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

In [24]:
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [25]:
# math score to series
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [30]:
# kor, eng score to df
df[['국어','수학']]

국어  수학
춘향  80  90
몽룡  90  60
향단  70  80
방자  30  70

In [33]:
# Add new col with mean of scores
df.values

array([[80, 90, 90],
       [90, 70, 60],
       [70, 60, 80],
       [30, 40, 70]])

In [36]:
df['평균'] = np.mean(df.values, axis=1).round(1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  40  70  46.7

In [37]:
df.mean(axis=1)

춘향    86.675
몽룡    73.325
향단    70.000
방자    46.675
dtype: float64

In [39]:
# Fix '방자' eng score 80 and recalculate mean
del df['평균']
df['영어']['방자'] = 80
df['평균'] = np.round(df.mean(axis=1), 1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

In [41]:
# Make '춘향' score to df
df[:'춘향']

국어  영어  수학    평균
춘향  80  90  90  86.7

In [43]:
df.T[['춘향']]

춘향
국어  80.0
영어  90.0
수학  90.0
평균  86.7

In [44]:
# take out 2 row in the middle
df.head(3).tail(2)

국어  영어  수학    평균
몽룡  90  70  60  73.3
향단  70  60  80  70.0

In [49]:
# make '향단' score to series
df.T['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64

In [47]:
df['영어']['방자']

80